### ISSUE TITLE
Dataset extraction 

### ISSUE THREAD

**Issue by zuther77** [SreemukhMantripragada/SpeechEnhancement#2]
Hi, I downloaded the Mozilla comman voice dateset for english language. It gave me a 51gb .tar file named 'en.tar'.
I extracted the file using winRaR as I'm working on windows. It only gave me a single file named en with no directories like en/train.tsv

Please can u tell me how u got those directories?

**Comment by SreemukhMantripragada** [comment]
I suggest that you use the tarfile library to extract. 
A code something like this does the job.
`import tarfile`
`tar= tarfile.open('en.tar') `
`tar.extractall('path_to_dest')`
`tar.close()`

**Comment by zuther77** [comment]
thanks for this worked like a charm. Turns out windows recently added tar extraction in cmd itself
I extracted the dataset and tried running the notebook now I'm getting the below error: 

I ran the last cell in the Data Processing.ipynb -->>
tf_record(clean_val_paths,ub_val_paths, 2000, "val")
tf_record(clean_train_paths,ub_train_paths,10000,"train")

Output -->>

RuntimeError                              Traceback (most recent call last)
~\anaconda3\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    145     try:
--> 146         with sf.SoundFile(path) as sf_desc:
    147             sr_native = sf_desc.samplerate

~\anaconda3\lib\site-packages\soundfile.py in __init__(self, file, mode, samplerate, channels, subtype, endian, format, closefd)
    628                                          format, subtype, endian)
--> 629         self._file = self._open(file, mode_int, closefd)
    630         if set(mode).issuperset('r+') and self.seekable():

~\anaconda3\lib\site-packages\soundfile.py in _open(self, file, mode_int, closefd)
   1182             raise TypeError("Invalid file: {0!r}".format(self.name))
-> 1183         _error_check(_snd.sf_error(file_ptr),
   1184                      "Error opening {0!r}: ".format(self.name))

~\anaconda3\lib\site-packages\soundfile.py in _error_check(err, prefix)
   1356         err_str = _snd.sf_error_number(err)
-> 1357         raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
   1358 

RuntimeError: Error opening 'en\\clips\\common_voice_en_18773163.mp3': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

NoBackendError                            Traceback (most recent call last)
<ipython-input-38-b82a4da6b589> in <module>
      1 # Functions are called to create respective tfrecord files
      2 
----> 3 tf_record(clean_val_paths,ub_val_paths, 2000, "val")
      4 tf_record(clean_train_paths,ub_train_paths,10000,"train")

<ipython-input-27-3521375dd389> in tf_record(clean_files, noise_files, size, type_)
     31         out = []
     32         for file in clean_files_sub:
---> 33             out.append(process(file, noise_files))
     34         gc.collect()
     35 

<ipython-input-25-317a8fb83355> in process(file, noise_files)
     17 
     18     #Load Audio file
---> 19     audio, sr = librosa.load(file,sr=fs)
     20     audio = librosa.util.normalize(audio)
     21 

~\anaconda3\lib\site-packages\librosa\core\audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    161         if isinstance(path, (str, pathlib.PurePath)):
    162             warnings.warn("PySoundFile failed. Trying audioread instead.")
--> 163             y, sr_native = __audioread_load(path, offset, duration, dtype)
    164         else:
    165             raise (exc)

~\anaconda3\lib\site-packages\librosa\core\audio.py in __audioread_load(path, offset, duration, dtype)
    185 
    186     y = []
--> 187     with audioread.audio_open(path) as input_file:
    188         sr_native = input_file.samplerate
    189         n_channels = input_file.channels

~\anaconda3\lib\site-packages\audioread\__init__.py in audio_open(path, backends)
    114 
    115     # All backends failed!
--> 116     raise NoBackendError()

NoBackendError:
